create table if not exists public.profile_badge_definitions (
  badge_key text primary key,
  name text not null,
  description text not null default '',
  icon text not null default '★',
  category text not null default 'Achievement',
  award_type text not null check (award_type in ('achievement','admin')),
  achievement_key text unique references public.achievement_definitions(achievement_key) on update cascade on delete set null,
  tier text not null default 'standard',
  sort_order integer not null default 0,
  visible boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.player_profile_badges (
  player_id uuid not null references public.profiles(id) on delete cascade,
  badge_key text not null references public.profile_badge_definitions(badge_key) on update cascade on delete cascade,
  source text not null check (source in ('achievement','admin')),
  awarded_by uuid references public.profiles(id) on delete set null,
  awarded_at timestamptz not null default now(),
  primary key (player_id, badge_key)
);

create table if not exists public.player_profile_badge_equipment (
  player_id uuid primary key references public.profiles(id) on delete cascade,
  badge_key text references public.profile_badge_definitions(badge_key) on update cascade on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.profile_badge_admin_log (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.profiles(id) on delete cascade,
  badge_key text not null references public.profile_badge_definitions(badge_key) on update cascade on delete restrict,
  action text not null check (action in ('assign','revoke')),
  admin_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists player_profile_badges_badge_idx on public.player_profile_badges(badge_key, player_id);
create index if not exists profile_badge_admin_log_player_idx on public.profile_badge_admin_log(player_id, created_at desc);

alter table public.profile_badge_definitions enable row level security;
alter table public.player_profile_badges enable row level security;
alter table public.player_profile_badge_equipment enable row level security;
alter table public.profile_badge_admin_log enable row level security;

revoke all on public.profile_badge_definitions from anon, authenticated;
revoke all on public.player_profile_badges from anon, authenticated;
revoke all on public.player_profile_badge_equipment from anon, authenticated;
revoke all on public.profile_badge_admin_log from anon, authenticated;

grant select, insert, update, delete on public.profile_badge_definitions to service_role;
grant select, insert, update, delete on public.player_profile_badges to service_role;
grant select, insert, update, delete on public.player_profile_badge_equipment to service_role;
grant select, insert, update, delete on public.profile_badge_admin_log to service_role;
grant usage, select on sequence public.profile_badge_admin_log_id_seq to service_role;

insert into public.profile_badge_definitions
  (badge_key, name, description, icon, category, award_type, achievement_key, tier, sort_order, visible)
values
  ('gazda', 'Gazda', 'Awarded by Brasta admins.', '👑', 'Special', 'admin', null, 'special', 5, true),
  ('founder', 'Founder', 'Reserved for Brasta founders.', '😎', 'Special', 'admin', null, 'special', 6, true),
  ('winner', 'Winner', 'Win your first Brasta match.', '🏆', 'Achievement', 'achievement', 'first_win', 'standard', 100, true),
  ('builder', 'Builder', 'Make your first build.', '🔨', 'Achievement', 'achievement', 'builder', 'standard', 110, true),
  ('brasta', 'Brasta!', 'Score your first Brasta.', '✨', 'Achievement', 'achievement', 'first_brasta', 'standard', 120, true),
  ('brasta_veteran', 'Brasta Veteran', 'Score 100 Brastas across your career.', '💫', 'Achievement', 'achievement', 'brasta_100', 'silver', 130, true),
  ('back_to_back', 'Back-to-Back', 'Score Brastas on two consecutive personal turns.', '⚡', 'Achievement', 'achievement', 'brasta_streak_2', 'bronze', 140, true),
  ('triple_threat', 'Triple Threat', 'Score Brastas on three consecutive personal turns.', '🔥', 'Achievement', 'achievement', 'brasta_streak_3', 'silver', 150, true),
  ('brasta_run', 'Brasta Run', 'Score Brastas on four consecutive personal turns.', '💥', 'Achievement', 'achievement', 'brasta_streak_4', 'gold', 160, true),
  ('unstoppable', 'Unstoppable', 'Score Brastas on five consecutive personal turns.', '⚡', 'Achievement', 'achievement', 'brasta_streak_5', 'gold', 170, true),
  ('big_game_hunter', 'Big Game Hunter', 'Capture the Big 10.', '🔟', 'Achievement', 'achievement', 'big_game', 'standard', 180, true),
  ('sweep_artist', 'Sweep Artist', 'Sweep the table with 10 Jacks.', '🧹', 'Achievement', 'achievement', 'sweep_artist', 'bronze', 190, true),
  ('fire_marshal', 'Fire Marshal', 'Successfully call 10 burns.', '🚒', 'Achievement', 'achievement', 'fire_marshal', 'bronze', 200, true),
  ('scorched_earth', 'Scorched Earth', 'See opponents burn 100 Jacks across your career.', '🔥', 'Achievement', 'achievement', 'opponent_jack_burn_100', 'legendary', 210, true),
  ('hot_hand', 'Hot Hand', 'Reach a three-match win streak.', '🔥', 'Achievement', 'achievement', 'hot_hand', 'bronze', 220, true),
  ('on_fire', 'On Fire', 'Reach a five-match win streak.', '🔥', 'Achievement', 'achievement', 'on_fire', 'silver', 230, true),
  ('card_collector', 'Card Collector', 'Capture 100 cards across your career.', '🃏', 'Achievement', 'achievement', 'capture_100', 'bronze', 240, true),
  ('table_regular', 'Table Regular', 'Complete 25 Brasta matches.', '🎴', 'Achievement', 'achievement', 'veteran_25', 'bronze', 250, true)
on conflict (badge_key) do update set
  name = excluded.name,
  description = excluded.description,
  icon = excluded.icon,
  category = excluded.category,
  award_type = excluded.award_type,
  achievement_key = excluded.achievement_key,
  tier = excluded.tier,
  sort_order = excluded.sort_order,
  visible = excluded.visible;

create or replace function public.brasta_grant_profile_badge_for_achievement()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.unlocked_at is not null then
    insert into public.player_profile_badges (player_id, badge_key, source, awarded_by, awarded_at)
    select new.player_id, d.badge_key, 'achievement', null, coalesce(new.unlocked_at, now())
    from public.profile_badge_definitions d
    where d.award_type = 'achievement'
      and d.achievement_key = new.achievement_key
    on conflict (player_id, badge_key) do nothing;
  end if;
  return new;
end;
$$;

revoke all on function public.brasta_grant_profile_badge_for_achievement() from public, anon, authenticated;
grant execute on function public.brasta_grant_profile_badge_for_achievement() to service_role;

drop trigger if exists brasta_player_achievement_badge_grant on public.player_achievements;
create trigger brasta_player_achievement_badge_grant
after insert or update of unlocked_at on public.player_achievements
for each row
when (new.unlocked_at is not null)
execute function public.brasta_grant_profile_badge_for_achievement();

insert into public.player_profile_badges (player_id, badge_key, source, awarded_by, awarded_at)
select pa.player_id, d.badge_key, 'achievement', null, pa.unlocked_at
from public.player_achievements pa
join public.profile_badge_definitions d
  on d.award_type = 'achievement'
 and d.achievement_key = pa.achievement_key
where pa.unlocked_at is not null
on conflict (player_id, badge_key) do nothing;

create or replace function public.brasta_equip_profile_badge(p_player_id uuid, p_badge_key text default null)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_badge_key text := nullif(trim(coalesce(p_badge_key, '')), '');
begin
  if not exists (select 1 from public.profiles where id = p_player_id) then
    raise exception 'Player profile not found.';
  end if;

  if v_badge_key is not null and not exists (
    select 1 from public.player_profile_badges
    where player_id = p_player_id and badge_key = v_badge_key
  ) then
    raise exception 'You have not unlocked that badge.';
  end if;

  insert into public.player_profile_badge_equipment (player_id, badge_key, updated_at)
  values (p_player_id, v_badge_key, now())
  on conflict (player_id) do update
    set badge_key = excluded.badge_key,
        updated_at = excluded.updated_at;

  return v_badge_key;
end;
$$;

revoke all on function public.brasta_equip_profile_badge(uuid, text) from public, anon, authenticated;
grant execute on function public.brasta_equip_profile_badge(uuid, text) to service_role;

create or replace function public.brasta_admin_set_profile_badge(
  p_player_id uuid,
  p_badge_key text,
  p_admin_id uuid,
  p_assign boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_badge_key text := trim(coalesce(p_badge_key, ''));
begin
  if not exists (
    select 1 from public.profile_badge_definitions
    where badge_key = v_badge_key and award_type = 'admin'
  ) then
    raise exception 'That badge is not admin assignable.';
  end if;

  if not exists (select 1 from public.profiles where id = p_player_id) then
    raise exception 'Player profile not found.';
  end if;

  if p_assign then
    insert into public.player_profile_badges (player_id, badge_key, source, awarded_by, awarded_at)
    values (p_player_id, v_badge_key, 'admin', p_admin_id, now())
    on conflict (player_id, badge_key) do update
      set source = 'admin', awarded_by = excluded.awarded_by;

    insert into public.profile_badge_admin_log (player_id, badge_key, action, admin_id)
    values (p_player_id, v_badge_key, 'assign', p_admin_id);
  else
    delete from public.player_profile_badges
    where player_id = p_player_id and badge_key = v_badge_key and source = 'admin';

    update public.player_profile_badge_equipment
    set badge_key = null, updated_at = now()
    where player_id = p_player_id and badge_key = v_badge_key;

    insert into public.profile_badge_admin_log (player_id, badge_key, action, admin_id)
    values (p_player_id, v_badge_key, 'revoke', p_admin_id);
  end if;
end;
$$;

revoke all on function public.brasta_admin_set_profile_badge(uuid, text, uuid, boolean) from public, anon, authenticated;
grant execute on function public.brasta_admin_set_profile_badge(uuid, text, uuid, boolean) to service_role;
